version: '3.8'

services:
  # PostgreSQL with extensions
  postgres:
    image: postgres:15-alpine
    container_name: aether_postgres
    environment:
      POSTGRES_DB: aether_prod
      POSTGRES_USER: ${DB_USER:-aether_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-aether_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql
    ports:
      - "5432:5432"
    networks:
      - aether_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-aether_user} -d aether_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis with persistence
  redis:
    image: redis:7-alpine
    container_name: aether_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - aether_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis_password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: aether_backend
    ports:
      - "8000:8000"
    environment:
      # App
      ENVIRONMENT: production
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY}
      
      # Database
      DATABASE_URL: postgresql://${DB_USER:-aether_user}:${DB_PASSWORD:-aether_password}@postgres:5432/aether_prod
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      
      # AI Services
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      
      # Plaid
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_ENVIRONMENT: ${PLAID_ENVIRONMENT:-sandbox}
      
      # AWS
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-aether-documents}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      CLOUDFRONT_URL: ${CLOUDFRONT_URL}
      
      # Email
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@aether.ai}
      
      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      
      # Monitoring
      SENTRY_DSN: ${SENTRY_DSN}
      LOG_LEVEL: INFO
      
      # Security
      JWT_LEEWAY: "30"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      REFRESH_TOKEN_EXPIRE_DAYS: "7"
      
      # Performance
      DATABASE_POOL_SIZE: "20"
      DATABASE_MAX_OVERFLOW: "40"
      API_TIMEOUT: "30"
      
    volumes:
      - ./backend:/app
      - ./ml/models:/app/ml/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - aether_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: aether_celery_worker
    command: >
      celery -A app.workers.celery_app worker
      --loglevel=info
      --concurrency=${CELERY_CONCURRENCY:-4}
      --hostname=worker@%h
      --queues=default,documents,transactions,reports,email
      --max-tasks-per-child=1000
    environment:
      DATABASE_URL: postgresql://${DB_USER:-aether_user}:${DB_PASSWORD:-aether_password}@postgres:5432/aether_prod
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./backend:/app
      - ./ml/models:/app/ml/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - aether_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Celery Beat
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: aether_celery_beat
    command: celery -A app.workers.celery_app beat --loglevel=info --pidfile=
    environment:
      DATABASE_URL: postgresql://${DB_USER:-aether_user}:${DB_PASSWORD:-aether_password}@postgres:5432/aether_prod
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - aether_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: aether_frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://api.aether.ai}
      VITE_WS_URL: ${VITE_WS_URL:-wss://api.aether.ai}
      VITE_ENVIRONMENT: production
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
      VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
      VITE_PLAID_PUBLIC_KEY: ${VITE_PLAID_PUBLIC_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aether_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: aether_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend/dist:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - aether_network
    restart: unless-stopped

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: aether_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - aether_network
    restart: unless-stopped

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: aether_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - aether_network
    restart: unless-stopped

  # Vector for logs
  vector:
    image: timberio/vector:latest-alpine
    container_name: aether_vector
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./logs:/var/log/aether
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8686:8686"
    networks:
      - aether_network
    restart: unless-stopped

  # Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: aether_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - aether_network
    restart: unless-stopped

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: aether_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@aether.ai}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - aether_network
    restart: unless-stopped

networks:
  aether_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  pgadmin_data:
